### ISSUE TITLE
cp ressources in website’s source code

### ISSUE THREAD

**Issue by ballmannweber** [timvermaercke/craft-cookie-though#2]
this plugin wrongfully places craft’s cp ressources like css and js in my code, like…

`    <meta name="msapplication-TileColor" content="#fd6370">
    <meta name="theme-color" content="#fd6370">
    <link href="https://domain.de/cpresources/10427ac0/selectize.css?v=1631128605" rel="stylesheet">
    <link href="https://domain.de/cpresources/592cc94e/css/craft.css?v=1631356836" rel="stylesheet">
    <link href="https://domain.de/cpresources/592cc94e/css/charts.css?v=1631356836" rel="stylesheet">
    <script>
    window.Craft = {
        "actionTrigger": "actions",
        "actionUrl": "https:\/\/domain.de\/index.php?p=actions\/",
        "allowAdminChanges": true,
        "allowUpdates": true,
        "allowUppercaseInSlug": false,
        "announcements": [],
        "apiParams": null,
        "asciiCharMap": {
            "Á": "A",
            "á": "a",
            "Ä": "Ae",
            "ä": "ae",
            "À": "A",
            "à": "a",
            "Â": "A",
            "â": "a",
            "É": "E",
            "é": "e",
            "Ë": "E",
            "ë": "e",
            "È": "E",
            "è": "e",
            "Ê": "E",
            "ê": "e",
            "Í": "I",
            "í": "i",
            "Ï": "I",
            "ï": "i",
            "Ì": "I",
            "ì": "i",
            "Î": "I",
            "î": "i",`

or

` <script src="https://domain.de/cpresources/9d674752/axios.min.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/4a997715/d3.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/e706c036/element-resize-detector.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/c8966bc3/jquery.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/43986b86/jquery.mobile-events.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/d9199cbe/velocity.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/79246093/garnish.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/97b0071b/jquery-ui.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/c53e3356/jquery.payment.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/9e1dddc/datepicker-de.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/443c5744/picturefill.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/10427ac0/selectize.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/5cd456ba/jquery.fileupload.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/1a2e3e4a/xregexp-all.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/6c62b4ad/fabric.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/507769ad/iframeResizer.js?v=1631128605"></script>
    <script src="https://domain.de/cpresources/592cc94e/js/Craft.min.js?v=1631356836"></script>
    <script src="https://unpkg.com/cookie-though@1.2.0"></script>
    <script src="https://domain.de/cpresources/dd9f3ceb/js/CookieThough.js?v=1631356836"></script>`

**Comment by timvermaercke** [comment]
Hi @ballmannweber, this should be fixed in [1.0.3](https://github.com/timvermaercke/craft-cookie-though/releases/tag/1.0.3).
